name: 07-experssion
on:
  push:
  workflow_dispatch:
        inputs:
          debug: 
            types: boolean
      default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
         - name: '[debug] print start-up data' 
           if: ${{inputs.debug}}
           run: |
               echo "Triggered by ${{github.event_name }}"
               echo "Branch ${{ github.ref }}"
               echo "commit SHA ${{github.sha }}"
               echo "runner os ${{ github.runners.os }}"
               echo ""
         - name: '[debug] print when triggered form main'
           if: ${{inputs.debug && github.ref=='ref/head/main'}} 
           run: |
                echo "I was triggering from main"    
         - name : Greeting
           run: echo "Hello World"
